#!/bin/sh

[ "$PLUTO_PEER_CLIENT" = "0.0.0.0/0" ] || exit 0

. /lib/functions/network.sh

network_get_subnet lan_subnet lan

case "$PLUTO_VERB:" in
	up-client:)
		[ "$(uci -q get ipsec.${PLUTO_CONNECTION##*-}.defaultroute)" = "1" ] || exit 0
		iptables -I postrouting_wan_rule -t nat -s "$lan_subnet" \
	    -m comment --comment "Added by Strongswan hotplug" \
	    -j SNAT --to $PLUTO_MY_SOURCEIP4_1
	    echo "Added firewall SNAT rule: from $lan_subnet to $PLUTO_MY_SOURCEIP4_1"
		;;
	down-client:)
		iptables -D postrouting_wan_rule -t nat -s "$lan_subnet" \
	    -m comment --comment "Added by Strongswan hotplug" \
	    -j SNAT --to $PLUTO_MY_SOURCEIP4_1
	     echo "Removed firewall SNAT rule: from $lan_subnet to $PLUTO_MY_SOURCEIP4_1t"
		;;
esac
