#!/bin/sh
module_vid=`uci get -q system.module.vid`
module_pid=`uci get -q system.module.pid`
bands=`uci get -q simcard.bands`
bandval=`uci get -q simcard.sim1.bandval`
ltebandval=`uci get -q simcard.sim1.ltebandval`
bandval2=`uci get -q simcard.sim2.bandval`
ltebandval2=`uci get -q simcard.sim2.ltebandval`
auto_apn=`uci get -q simcard.sim1.auto_apn`
force_apn=`uci get -q simcard.sim1.force_apn`
auto_apn2=`uci get -q simcard.sim2.auto_apn`
force_apn2=`uci get -q simcard.sim2.force_apn`

if [ -n "$force_apn" ]; then
    uci set simcard.sim1.auto_apn="0"
elif [ "$auto_apn" == "0" ]; then
    uci set simcard.sim1.force_apn="-1"
fi

if [ -n "$force_apn2" ]; then
    uci set simcard.sim2.auto_apn="0"
elif [ "$auto_apn2" == "0" ]; then
    uci set simcard.sim2.force_apn="-1"
fi

if [ "$module_vid" == "2C7C" ] && [ "$module_pid" == "0125" ]; then
    if [ -z "$bands" ]; then
	    uci set simcard.bands=bands
    fi
    if [ -z "$bandval" ]; then
        uci set -q simcard.sim1.bandval="ffff"
    fi
    if [ -z "$ltebandval" ]; then
        uci set -q simcard.sim1.ltebandval="1a0000800d5"
    fi
    if [ -z "$bandval2" ]; then
        uci set -q simcard.sim2.bandval="ffff"
    fi
    if [ -z "$ltebandval2" ]; then
        uci set -q simcard.sim2.ltebandval="1a0000800d5"
    fi
	uci commit simcard
fi
exit 0
