#!/bin/sh

. /lib/functions.sh

iterate_main() {
	config_get enabled "$1" enabled
	config_get debug "$1" debug

	uci set quagga.nhrp=nhrp_global
	uci set quagga.nhrp.enabled=$enabled
	uci set quagga.nhrp.debug=$debug
	uci commit quagga
}

iterate_instance() {
	config_get enabled "$1" enabled
	config_get proto_address "$1" proto_address
	config_get network_id "$1" network_id
	config_get holdtime "$1" holdtime
	config_get interface "$1" interface
	config_get ipsec_support "$1" ipsec_support
	config_get ipsec_instance "$1" ipsec_instance
	config_get nbma_address "$1" nbma_address
	config_get tunnel_source "$1" tunnel_source

	uci set quagga."$1"=nhrp_instance
	uci set quagga."$1".enabled="$enabled"
	uci set quagga."$1".proto_address="$proto_address"
	uci set quagga."$1".network_id="$network_id"
	uci set quagga."$1".holdtime="$holdtime"
	uci set quagga."$1".interface="$interface"
	uci set quagga."$1".ipsec_support="$ipsec_support"
	uci set quagga."$1".ipsec_instance="$ipsec_instance"
	uci set quagga."$1".nbma_address="$nbma_address"
	uci set quagga."$1".tunnel_source="$tunnel_source"
	uci commit quagga
}

if [[ -f "/etc/config/nhrpd" ]]; then
	config_load nhrpd
	config_foreach iterate_main "nhrp_global"
	config_foreach iterate_instance "nhrp"
	rm /etc/config/nhrpd
fi