#!/bin/sh

. /lib/functions.sh

check_ioman_status_flgs() {
	local section="$1"
	local bad_fw=0

	config_get default_DOUT2_status "$section" default_DOUT2_status
	config_get default_DOUT1_status "$section" default_DOUT1_status
	config_get default_DOUT3_status "$section" default_DOUT3_status
	config_get active_DIN3_status "$section" active_DIN3_status "N/A"
	config_get active_DIN2_status "$section" active_DIN2_status "N/A"
	config_get active_DIN1_status "$section" active_DIN1_status "N/A"

	if [ -n "$default_DOUT3_status" -o -n "$default_DOUT2_status" -o -n "$default_DOUT1_status" ]; then
		[ "$active_DIN3_status" = "N/A" ] && {
			uci set ioman.@ioman[0].active_DIN3_status=0
			bad_fw=1
		}
		[ "$active_DIN2_status" = "N/A" ] && {
			uci set ioman.@ioman[0].active_DIN2_status=0
			bad_fw=1
		}

		[ $bad_fw -eq 1 ] && uci set ioman.@ioman[0].active_DOUT3_status=0
	else
		[ "$active_DIN3_status" = "N/A" ] && uci set ioman.@ioman[0].active_DIN3_status=1
		[ "$active_DIN2_status" = "N/A" ] && uci set ioman.@ioman[0].active_DIN2_status=1
	fi

	[ "$active_DIN2_status" = "N/A" ] && uci set ioman.@ioman[0].active_DIN1_status=1
}

config_load "ioman"
config_foreach check_ioman_status_flgs "ioman" 
uci commit ioman
