#!/bin/sh /etc/rc.common

SAMBA_CONFIG=`uci show samba | grep enable=\'1\' | wc -l`
SAMBA_SERVICE=`opkg list-installed | grep samba36-server | wc -l`
SAMBA_CUSTOM=`cat /etc/package_restore.txt | grep samba36-server | wc -l`
TR_CONFIG=`uci get easycwmp.@acs[0].enabled`
TR_SERVICE=`opkg list-installed | grep easycwmp | wc -l`
TR_CUSTOM=`cat /etc/package_restore.txt | grep easycwmp | wc -l`
SNMP_CONFIG=`uci show snmpd | grep enabled=\'1\' | wc -l`
SNMP_SERVICE=`opkg list-installed | grep snmpd | wc -l`
SNMP_CUSTOM=`cat /etc/package_restore.txt | grep snmpd | wc -l`
UPNP_CONFIG=`uci get upnpd.config.enabled`
UPNP_SERVICE=`opkg list-installed | grep miniupnpd | wc -l`
UPNP_CUSTOM=`cat /etc/package_restore.txt | grep miniupnpd | wc -l`

if [ "$SAMBA_CONFIG" -gt 0 -a "$SAMBA_SERVICE" -eq 0 -a "$SAMBA_CUSTOM" -eq 0 ]; then
	echo "tlt_custom_pkg_samba36-server - USB Tools" >> /etc/package_restore.txt
elif [ "$SAMBA_SERVICE" -eq 0 -a "$SAMBA_CUSTOM" -eq 0 ]; then
	rm /etc/config/samba 2>/dev/null
fi

if [ "$TR_CONFIG" == "1" -a "$TR_SERVICE" -eq 0 -a "$TR_CUSTOM" -eq 0 ]; then
	echo "tlt_custom_pkg_easycwmp - TR-069" >> /etc/package_restore.txt
elif [ "$TR_SERVICE" -eq 0 -a "$TR_CUSTOM" -eq 0 ]; then
	rm /etc/config/easycwmp 2>/dev/null
fi

if [ "$SNMP_CONFIG" -gt 0 -a "$SNMP_SERVICE" -eq 0 -a "$SNMP_CUSTOM" -eq 0 ]; then
	echo "tlt_custom_pkg_snmpd - SNMP" >> /etc/package_restore.txt
elif [ "$SNMP_SERVICE" -eq 0 -a "$SNMP_CUSTOM" -eq 0 ]; then
	rm /etc/config/snmpd 2>/dev/null
fi

if [ "$UPNP_CONFIG" == "1" -a "$UPNP_SERVICE" -eq 0 -a "$UPNP_CUSTOM" -eq 0 ]; then
	echo "tlt_custom_pkg_miniupnpd - UPNP" >> /etc/package_restore.txt
elif [ "$UPNP_SERVICE" -eq 0 -a "$UPNP_CUSTOM" -eq 0 ]; then
	rm /etc/config/upnpd 2>/dev/null
fi


if [ -f "/etc/package_restore.txt" -o -d "/etc/backup_packages/" ]; then
	/etc/package_restore.sh &
	exit 1
fi

exit 0
