#!/bin/sh

. /lib/functions.sh

SECTION_FOUND=0

fix_button(){
	local sec=$1 handler

	config_get handler "$sec" handler

	[ "$handler" = "firstboot && reboot" ] && {
		uci -q set system.${sec}.handler="firstboot"
	}
}

find_section(){
	local value

	config_get value "$1" "$2"
	[ "$value" = "$3" ] && SECTION_FOUND=1
}

config_load system
config_foreach fix_button button
config_foreach find_section button handler default

[ $SECTION_FOUND -eq 0 ] && {
	uci -q batch <<-EOF
		add system button
		set system.@button[-1].min=6
		set system.@button[-1].max=11
		set system.@button[-1].handler=default
		set system.@button[-1].action=released
		reorder system.@button[-1]=2
EOF
}

uci -q commit system

exit 0
