#!/bin/sh

#renaming section name/type "profile" to "general"

[[ "$(uci -q get profiles.profiles)" == "profiles" ]] && {
	uci rename profiles.profiles=general
	uci commit
	sed -i 's/config profiles/config general/g' /etc/config/profiles
}
[[ "$(uci -q get profiles.general.profile)" == "" ]] && {
	uci -q set profiles.general.profile=default
}
[[ "$(uci -q get profiles.scheduler)" == "scheduler" ]] || {
	uci -q set profiles.scheduler='scheduler'
}

#Legacy profiles.
#There was no config sections in old times. If any old fashion profile found, generate config for it.
files="$(ls /etc/profiles/*.tar.gz)"

[ -n "$files" ] && {
    for file in $files; do
        count=$((count+1))
        file=$(basename $file)
        name=${file%%_[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].*}
        
        [ "$file" != "$name" -a "$(uci -q get profiles.$name)" == "" ] && {
                date=$(echo $file | grep -o "[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}")
                uci -q set profiles.$name='profile'
                uci -q set profiles.$name.archive="$file"
                uci -q set profiles.$name.md5file="${name}_${date}.md5"
                uci -q set profiles.$name.id="$count"
                [ -n "$date" ] && {
                    uci -q set profiles.$name.updated="$(date -d $date +%s)"
                }
        }
    done
}

uci -q commit profiles

