#!/bin/sh

. /lib/functions.sh

min=5
max=100
rst_file=/tmp/rst_btn

handler_reboot(){
	echo "REBOOT" > /dev/console
	/usr/bin/ledman --clean
	sync
	reboot -b
	exit
}

handler_firstboot(){
	echo "FACTORY RESET" > /dev/console
	/usr/bin/ledman --clean
	firstboot -y && reboot -b &
	exit
}

handler_default(){
	local tar_file="/etc/default-config/config.tar.gz"

	[ ! -f "$tar_file" ] && handler_firstboot

	echo "RESTORE TO DEFAULT CONFIG" > /dev/console
	/sbin/user_defaults
	reboot -c
	exit
}

handle () {
    local action handler min max enabled

	config_get enabled "${1}" enabled 1
	[ "$enabled" -ne 1 ] && return

    config_get action "${1}" action
    config_get handler "${1}" handler
    config_get min "${1}" min
    config_get max "${1}" max

    logger "Action ${ACTION}, handler ${handler}, min ${min}, max ${max}, SEEN ${SEEN}"

    [ "${ACTION}" = "${action}" -a -n "${handler}" ] && {
        [ -z "${min}" -o -z "${max}" ] && eval handler_${handler}
        [ -n "${min}" -a -n "${max}" ] && {
            [ "${min}" -le "${SEEN}" -a "${max}" -ge "${SEEN}" ] && {
            	logger "eval handler_${handler}"
            	eval handler_${handler}
			}
        }
    }
}

if [ "${ACTION}" = "pressed" ]; then
	logger "$BUTTON was $ACTION after $SEEN seconds"
else
	logger "$BUTTON was $ACTION for $SEEN seconds"
fi

[ "${ACTION}" = "pressed" ] && {
	/usr/bin/ledman --bar
	touch $rst_file
}

if [ "${ACTION}" = "released" ] && [ ! -f $rst_file ]; then
	exit
fi

config_load buttons
config_foreach handle button

[ "${ACTION}" = "released" ] && {
	/usr/bin/ledman --auto
	rm $rst_file
}
