#!/bin/sh /etc/rc.common
# Copyright (C) 2021 Teltonika

START=51

USE_PROCD=1
PROG="/usr/sbin/telnetd"

service_triggers() {
	procd_add_reload_trigger "telnetd"
}

start_instance() {
	local enabled port

	config_get enabled "$1" enable 0
	[ "$enabled" -ne 1 ] && return 0

	config_get port "$1" port 23

	procd_open_instance
	procd_set_param command "$PROG" -F -p "$port"
	procd_close_instance
}

start_service() {
	config_load "telnetd"
	config_foreach start_instance "telnetd"
}
