#ifndef AXTLS_VERSION
#define AXTLS_VERSION 0
#endif
#define TW_HOST "localhost"
#define TW_PORT 443
#define TW_APP_KEY "babababa-baba-baba-baba-babababababa"
#define CONNECT_RETRIES 3
#define TEST_FORCE_CONNECT FALSE
#define TEST_ENTITY_NAME "testEntityName"
#define TEST_ENTITY_NAME_1 "alphaEntityName"
#define TEST_ENTITY_NAME_2 "betaEntityName"
#define TEST_ENTITY_NAME_3 "gammaEntityName"
#define TEST_MULTIPLE_ENTITY_NAME_1 "testEntityName1"
#define TEST_MULTIPLE_ENTITY_NAME_2 "testEntityName2"
#define TEST_THING_NAME_1 "alphaThing"
#define TEST_THING_NAME_2 "betaThing"
#define TEST_THING_NAME_3 "gammaThing"
#define TEST_TIMEOUT 5
#define TEST_PROPERTY_NAME "testPropertyName"
#define TEST_PROPERTY_NAME_1 "alphaProperty"
#define TEST_PROPERTY_NAME_2 "betaProperty"
#define TEST_PROPERTY_NAME_3 "gammaProperty"
#define TEST_SERVICE_NAME "testServiceName"
#define TEST_SERVICE_NAME_1 "alphaService"
#define TEST_SERVICE_NAME_2 "betaService"
#define TEST_SERVICE_NAME_3 "gammaService"
#define TEST_EVENT_NAME "testEventName"
#define TEST_ASPECT_NAME "testAspectName"
#define TEST_PROPERTY_DESCRIPTION "testPropertyDescription"
#define TEST_SERVICE_DESCRIPTION "testServiceDescription"
#define TEST_EVENT_DESCRIPTION "testEventDescription"
#define TEST_ASPECT_DESCRIPTION "testAspectDescription"
#define TEST_PROXY_HOST "55.55.55.55"
#define TEST_PROXY_HOST_1 "66.66.66.66"
#define TEST_PROXY_PORT 443
#define TEST_PROXY_PORT_1 8443
#define TEST_PROXY_USER "proxyUser1"
#define TEST_PROXY_USER_1 "proxyUser1"
#define TEST_PROXY_PASS "proxyPass1"
#define TEST_PROXY_PASS_1 "proxyPass1"
#define TEST_SUBJECT_O "testSubjectO"
#define TEST_SUBJECT_OU "testSubjectOU"
#define TEST_SUBJECT_CN "testSubjectCN"
#define TEST_ISSUER_O "testIssuerO"
#define TEST_ISSUER_OU "testIssuerOU"
#define TEST_ISSUER_CN "testIssuerCN"
#define TEST_SUBJECT_O_1 "alphaTestSubjectO"
#define TEST_SUBJECT_OU_1 "alphaTestSubjectOU"
#define TEST_SUBJECT_CN_1 "alphaTestSubjectCN"
#define TEST_ISSUER_O_1 "alphaTestIssuerO"
#define TEST_ISSUER_OU_1 "alphaTestIssuerOU"
#define TEST_ISSUER_CN_1 "alphaTestIssuerCN"
#define TEST_OFFLINE_MSG_STORE_DIR "offlineMsgStoreDir"
#define TEST_PROPERTY_LIST_NAME "testPropertyListName"
#define TEST_CLIENT_KEY_PASS "testClientKeyPass"
#define TEST_CLIENT_KEY_FILE "testClientKeyFile"
#define TEST_CLIENT_KEY_TYPE 0
#define TEST_CLIENT_KEY_PASS_1 "alphaTestClientKeyPass"
#define TEST_CLIENT_KEY_FILE_1 "alphaTestClientKeyFile"
#define TEST_CLIENT_CERT_FILE "testClientCertFile"
#define TEST_CLIENT_CERT_FILE_1 "alphaTestClientCertFile"
#define TEST_CA_CERT_FILE "testCACertFile"
#define TEST_CA_CERT_FILE_1 "alphaTestCACertFile"
#define TEST_CA_CERT_TYPE 0
#define TEST_PRIMITIVE_INT_VALUE 42
#define TEST_ENTRY_NAME "testEntryName"
#define TEST_ENTRY_DESCRIPTION "testEntryDescription"
#define TEST_TYPE 0
#define TEST_GATEWAY_NAME "testGatewayName"
#define TEST_GATEWAY_NAME_1 "alphaTestGatewayName"
#define TEST_GATEWAY_TYPE "testGatewayType"
#define TEST_GATEWAY_TYPE_1 "alphaTestGatewayType"
#define TEST_LIST_BASIC_TEST_SIZE 100
#define TEST_DATA "testData"
#define TEST_CLAIM_NAME "testClaimName"
#define TEST_CLAIM_VALUE "testClaimValue"
#define TEST_LOG_PREAMBLE "testPreamble"
#define TEST_BIND_NAME "testBindName"
#define TEST_ID 1
#define TEST_SESSION_ID 1
#define TEST_ENDPOINT_ID 1
#define TEST_DS_ENTRY_NAME_1 "testDsEntryName1"
#define TEST_DS_ENTRY_NAME_2 "testDsEntryName2"
#define TEST_DS_ENTRY_NAME_3 "testDsEntryName3"
#define TEST_DS_ENTRY_DESCRIPTION_1 "testDsEntryDescription1"
#define TEST_DS_ENTRY_DESCRIPTION_2 "testDsEntryDescription2"
#define TEST_DS_ENTRY_DESCRIPTION_3 "testDsEntryDescription3"
#define TEST_BIND_BODY_NAME "testBindBodyName"
#define TEST_STRING "1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz The Quick Brown Fox Jumped Over The Lazy Dog"
#define TEST_STRING_LOWER "1234567890 abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz the quick brown fox jumped over the lazy dog"
#define TEST_STRING_UPPER "1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZ ABCDEFGHIJKLMNOPQRSTUVWXYZ THE QUICK BROWN FOX JUMPED OVER THE LAZY DOG"
#define TEST_STRING_CAT   "1234567890 abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz the quick brown fox jumped over the lazy dog1234567890 ABCDEFGHIJKLMNOPQRSTUVWXYZ ABCDEFGHIJKLMNOPQRSTUVWXYZ THE QUICK BROWN FOX JUMPED OVER THE LAZY DOG"
#define TEST_MAP_SIZE 100
#define TEST_CA_CERT_FILE "root_cert.pem"
#define TEST_CA_CERT_FILE_XL "root_cert_xl.pem"
#define TEST_CA_CERT_FILE_1 "alphaTestCACertFile"
#define TEST_PING_RATE 12345
#define TEST_PING_RATE_1 54321
#define TEST_CONNECT_TIMEOUT 12345
#define TEST_CONNECT_TIMEOUT_1 54321
#define TEST_CONNECT_RETRIES 4
#define TEST_CONNECT_RETRIES_1 5
#define SSL_FILETYPE_PEM 1