#!/bin/sh
# Copyright (C) 2015 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>

#common_execute_method_param "$parameter" "$permission" "$get_cmd" "$set_cmd" "xsd:$type" "$forcedinform"
#  $forcedinform should be set to 1 if the parameter is included in the inform message otherwise empty
#  Default of $type = string

#############################
#   Entry point functuons   #
#############################

prefix_list="$prefix_list $DMROOT.MobileInfo."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_MobileInfo"
entry_execute_method_list_forcedinform="$entry_execute_method_list_forcedinform  entry_execute_method_root_MobileInfo"
GSMCTL_BIN="/usr/sbin/gsmctl"
MDCOLLECTCTL_BIN=/usr/bin/mdcollectdctl

entry_execute_method_root_MobileInfo() {
	case "$1" in ""|"$DMROOT."|"$DMROOT.MobileInfo."*)
		common_execute_method_obj "$DMROOT.MobileInfo." "0"
		common_execute_method_param "$DMROOT.MobileInfo.RSSI" "0" "$GSMCTL_BIN -q" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.ConnState" "0" "$GSMCTL_BIN -j" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.NetState" "0" "$GSMCTL_BIN -g" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.ICCID" "0" "$GSMCTL_BIN -J" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.IMSI" "0" "$GSMCTL_BIN -x" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.RSCP" "0" "$GSMCTL_BIN -X" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.ECIO" "0" "$GSMCTL_BIN -E" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.RSRP" "0" "$GSMCTL_BIN -W" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.SINR" "0" "$GSMCTL_BIN -Z" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.RSRQ" "0" "$GSMCTL_BIN -M" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.CellID" "0" "$GSMCTL_BIN -C" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.Operator" "0" "$GSMCTL_BIN -o" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.OperatorNum" "0" "$GSMCTL_BIN -f" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.ConnType" "0" "$GSMCTL_BIN -t" "" "" "1"
		common_execute_method_param "$DMROOT.MobileInfo.SentToday" "0" "$MDCOLLECTCTL_BIN -cdaytx`gpio.sh get SIM`" ""
		common_execute_method_param "$DMROOT.MobileInfo.ReceivedToday" "0" "$MDCOLLECTCTL_BIN -cdayrx`gpio.sh get SIM`" ""
		common_execute_method_param "$DMROOT.MobileInfo.SentThisMonth" "0" "$MDCOLLECTCTL_BIN -cmonthtx`gpio.sh get SIM`" ""
		common_execute_method_param "$DMROOT.MobileInfo.ReceivedThisMonth" "0" "$MDCOLLECTCTL_BIN -cmonthrx`gpio.sh get SIM`" ""

		common_execute_method_obj "$DMROOT.MobileInfo.Modem." "0"
		common_execute_method_param "$DMROOT.MobileInfo.Modem.Model" "0" "$GSMCTL_BIN -m" "" ""
		common_execute_method_param "$DMROOT.MobileInfo.Modem.Manufacturer" "0" "$GSMCTL_BIN -w" "" ""
		common_execute_method_param "$DMROOT.MobileInfo.Modem.Serial" "0" "$GSMCTL_BIN -a" "" ""
		common_execute_method_param "$DMROOT.MobileInfo.Modem.Revision" "0" "$GSMCTL_BIN -y" "" ""
		common_execute_method_param "$DMROOT.MobileInfo.Modem.IMEI" "0" "$GSMCTL_BIN -i" "" ""
		common_execute_method_param "$DMROOT.MobileInfo.Modem.SimState" "0" "$GSMCTL_BIN -z" "" ""
		common_execute_method_param "$DMROOT.MobileInfo.Modem.PinState" "0" "$GSMCTL_BIN -u" ""
		common_execute_method_param "$DMROOT.MobileInfo.Modem.Temperature" "0" "$GSMCTL_BIN -c" ""

		return 0;
		;;
	esac
	return $E_INVALID_PARAMETER_NAME;
}

#######################################
#   Data model parameters functions   #
#######################################
