#!/bin/sh
. /lib/functions.sh
. /lib/functions/modem.sh

dev_name=$(mnf_info -n)

import_mwan(){
	config_get name "$1" name
	if [ "$name" = "wan" ]; then
		config_get network "$1" network
		for n in $network ; do
			metric=$(uci_get network "$n" metric)
			if [ -n "$metric" ]; then
				create_multiwan_iface "$n" "$(($metric - 1))"
				uci reorder mwan3."$n".interface="$metric"
			fi
		done
	fi
}

if [[ "$dev_name" == "TRB2"* ]]; then
	uci_remove mwan3 wan
	uci_remove mwan3 wan_member_mwan
	uci_remove mwan3 wan_member_balance
	uci_remove_list mwan3 mwan_default use_member wan_member_mwan
	uci_remove_list mwan3 balance_default use_member wan_member_balance
	uci_remove mwan3 @condition[0]
	config_load firewall
	config_foreach import_mwan zone
	uci_commit mwan3
fi

exit 0

