#!/bin/sh
PPP_IPPARAM="$6"
. /lib/netifd/netifd-proto.sh
. /lib/teltonika-functions.sh

proto_init_update "$IFNAME" 1 1
proto_set_keep 1
WAN_IFACE=`get_wan_section "ifname" "$IFNAME"`
evidpid="$(get_ext_vidpid_tlt)"


#/usr/sbin/wan_rule_man.sh "edit" "$IPLOCAL" "$WAN_IFACE"
[ -n "$PPP_IPPARAM" ] && {
	[ -n "$IPLOCAL" ] && proto_add_ipv4_address "$IPLOCAL" 32 "" "${IPREMOTE:-2.2.2.2}"
	[ -n "$IPREMOTE" ] && proto_add_ipv4_route 0.0.0.0 0 "$IPREMOTE"
	[ -n "$LLLOCAL" ] && proto_add_ipv6_address "$LLLOCAL" 128
	[ -n "$DNS1" ] && proto_add_dns_server "$DNS1"
	[ -n "$DNS2" -a "$DNS1" != "$DNS2" ] && proto_add_dns_server "$DNS2"
	#BUG: EC25-E disables unsolicited messages when establishing connection with ppp,
	# so after getting IP address, make sure unsolicided is enabled again
	if [ "$evidpid" = "2C7C:0125" ] && [ "$(pidof gsmd)" ]; then
		gsmctl -A AT+QCSQ=1
	fi
}
proto_send_update "$PPP_IPPARAM"

[ -d /etc/ppp/ip-up.d ] && {
	for SCRIPT in /etc/ppp/ip-up.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}

/sbin/chroutes

config_client_to_client=`echo $IFNAME | cut -d - -f 2`
enabled="uci get network.$config_client_to_client.client_to_client"
client_to_client_enabled=$($enabled)
destination=`echo $IPLOCAL | cut -d . -f 1,2,3`
routing_rule="route add -net $destination.0 netmask 255.255.255.0 dev $IFNAME"

if [ "$client_to_client_enabled" = "1" ]; then
	$($routing_rule)
fi
