#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	mount_root done
	rm -f /sysupgrade.tgz && sync

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	#some times soc usb does not start
	#workaround is reboot if usb not started
	platform=$(cat /proc/device-tree/platform)
	if [ $platform == "RUT9M" ] || [ $platform == "RUT2M" ]; then
		
		if [ -z $(uci -q get system.usbcheck.counter) ]; then
			uci -q set system.usbcheck=usbcheck
			uci -q set system.usbcheck.counter='0'
			uci -q set system.usbcheck.max='3'
			uci commit system
		fi

		if [ ! -d "/sys/bus/usb/drivers/usb/1-1" ]; then
			echo "USB system start up: FAILED... rebooting!"
			cnt=$(uci -q get system.usbcheck.counter)
			max=$(uci -q get system.usbcheck.max)
			if [ "$max" -gt "$cnt" ]; then
				cnt=$((cnt+1))
				uci -q set system.usbcheck.counter=$cnt
				uci commit system
				sync && reboot -f
			fi
		else
			echo "USB system start up: OK"
			uci -q set system.usbcheck.counter='0'
			uci commit system
		fi
	fi
}
