#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=1

. /lib/functions.sh
. /lib/teltonika-functions.sh
. /lib/functions/network.sh

start_tunnel(){
	local enabled proto peeraddr keep_alive keep_alive_interval dev localIP

	config_get proto "$1" "proto" ""
	config_get disabled "$1" "disabled" "0"

	[ "$disabled" != 1 -a "$proto" = "gre" ] && {

		config_get peeraddr "$1" "peeraddr" ""
		config_get keep_alive "$1" "keep_alive" "0"
		config_get keep_alive_interval "$1" "keep_alive_interval" "10"
		dev="gre4-$1"

		#localIP=$(get_active_wan "IP")
		network_find_wan "wanif" || {
			logger -t gre-tunnel "Can't find active WAN interface"
			return 1
		}

		network_get_ipaddr "localIP" "$wanif" || {
			logger -t gre-tunnel "Can't find WAN interface IP"
			return 1
		}

		procd_open_instance "$1"

		if [ "$keep_alive" = "1" ]; then
			procd_set_param command /usr/sbin/gre-tunnel-keepalive remote "$peeraddr" local "$localIP" dev "$dev" mode "both" seconds "$keep_alive_interval" debug 0
		else
			procd_set_param command /usr/sbin/gre-tunnel-keepalive remote "$peeraddr" local "$localIP" dev "$dev" mode "receive" debug 0
		fi

		procd_set_param respawn
		procd_close_instance
	}
}

service_triggers()
{
	procd_add_reload_trigger "network"
}

start_service() {
	config_load 'network'
	config_foreach start_tunnel 'interface'
}
