#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROC_BIN="/usr/sbin/kmod_man.sh"

start_service() {
	procd_open_instance
	procd_set_param command "$PROC_BIN"
	procd_close_instance
}

stop_service() {
	killall -q kmod_man.sh
}

reload_service() {
	restart
}

restart_service() {
	restart
}
