#!/bin/sh /etc/rc.common
START=76
STOP=39
USE_PROCD=1

enabled=`uci get mdcollectd.config.datalimit`
ppp_enabled=`uci get network.ppp.enabled`

start_service() {
	echo "start service"
	if [ "$enabled" = "1" ]; then
		command_line="/usr/bin/limit_guard start"
		procd_open_instance
		procd_set_param respawn 10
		procd_set_param command $command_line
		procd_close_instance
	fi
}


stop_service() {
	if [ "$enabled" = "0" ]; then
		if [ "$ppp_enabled" = "0" ]; then
			ifup ppp
		fi
	fi
	/usr/bin/limit_guard stop
}

restart () {
	stop
	start
}

reload_service() {
	stop
	start
}
