#!/bin/sh /etc/rc.common
# Copyright (C) 2015 Teltonika
. /lib/teltonika-functions.sh
. /lib/functions.sh

START=97
#STOP=19
#count=0

process_start()
{
	/usr/sbin/messaged status reboot
}

start()
{
	process_start
}
