#!/bin/sh /etc/rc.common

APP=/usr/sbin/modbus_tcp_master

USE_PROCD=1
START=99
STOP=99

ENABLED=""

check_registers(){
	config_get reg_enabled $1 "enabled"

	if [ "$reg_enabled" = "1" ]; then
		ENABLED="1"
	fi
}

check_tcp_slaves(){
	conf_name="$1"
	config_get enabled $1 "enabled"
	config_get section_id $1 "section_id"

	if [ "$enabled" = "1" ]; then
		config_foreach check_registers "register_$section_id"
	fi
}


start_service() {
	config_load modbus_tcp_master
	config_foreach check_tcp_slaves "tcp_slave"
	if [ "$ENABLED" = "1" ]; then
		procd_open_instance
		procd_set_param command $APP
		procd_set_param respawn ${respawn_threshold:-0} ${respawn_timeout:-10} ${respawn_retry:-0}
		procd_close_instance
	fi
}

reload_service(){
	procd_set_param file /etc/config/modbus_tcp_master /etc/config/modbus_master_alarms
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "modbus_tcp_master" "modbus_master_alarms"
}
