#!/bin/sh /etc/rc.common

# Copyright (C) 2014 Teltonika

. /lib/teltonika-functions.sh

START=50
STOP=51
USE_PROCD=1

start_service() {
	local enabled

	config_load ntpserver
	config_get enabled general enabled "0"

	[ "$enabled" == 0 ] && return

	logger -t "ntpd" "Starting NTP server"
	procd_open_instance
	procd_set_param respawn 0
	procd_set_param command "ntpd" -ln
	procd_close_instance
}