#!/bin/sh /etc/rc.common

START=99
STOP=99

. /lib/functions.sh
GPIO_SCRIPT="/sbin/gpio.sh"

script_run()
{
	local enabled action timeout timeout_time mode days interval_time gpio create
	local minutes="*"
	local hours="*"
	local param=""
	config_get enabled $1 enabled "0"
	config_get gpio $1 gpio
	config_get action $1 action
	config_get mode $1 mode
	config_get timeout $1 timeout "0"
	config_get timeout_time $1 timeout_time
	config_get days $1 day

	if [ "$enabled" == "1" ]; then

		if [ "$mode" == "fixed" ]; then
			config_get hours $1 fixed_hour "*"
			config_get minutes $1 fixed_minute "*"
			if [ "$hours" != "*" ] || [ "$minutes" != "*" ]; then
				create="1"
			fi
		elif [ "$mode" == "interval" ]; then
			config_get interval_time $1 interval_time
			if [ -n "$interval_time" ]; then
				hours=$((interval_time / 60))
				minutes=$((interval_time % 60))
				if [ "$hours" = "0" ]; then
					minutes="*/$minutes"
					hours="*"
				else
					minutes="0"
					hours="*/$hours"
				fi
				create="1"
			fi
		fi

		param="$param $gpio"

		if [ "$action" == "on" ]; then
			param="$param set"
		elif [ "$action" == "off" ]; then
			param="$param clear"
		fi

		if [ "$timeout" == "1" ]; then
			param="$param $timeout_time"
		fi

		if [ -z "$days" ]; then
			days="*"
		else
			days=${days// /,}
		fi

		if [ -n "$create" ]; then
			echo "$minutes $hours * * $days sh /sbin/output_control.sh $param" >> /etc/crontabs/root
		fi
	fi
}

init_default_values() {
	if [ ! -f "/tmp/default_io_values_are_set" ]; then
		touch /tmp/default_io_values_are_set
		
		DOUT1_default=`uci -q get ioman.ioman.default_DOUT1_status`
		DOUT2_default=`uci -q get ioman.ioman.default_DOUT2_status`
		DOUT3_default=`uci -q get ioman.ioman.default_DOUT3_status`
		
		in_out=`uci -q get hwinfo.hwinfo.in_out`
		in_out4pin=`uci -q get hwinfo.hwinfo.4pin_io`

		if [ -z "$DOUT1_default" ]; then
			DOUT1_default="0"
		fi
		if [ -z "$DOUT2_default" ]; then
			DOUT2_default="0"
		fi
		if [ -z "$DOUT3_default" ]; then
			DOUT3_default="0"
		fi
		if [ -z "$in_out" ]; then
			in_out="0"
		fi
		if [ -z "$in_out4pin" ]; then
			in_out4pin="0"
		fi

		if [ "$in_out" == "1" ]; then
			if [ "$DOUT1_default" == "1" ]; then
				$GPIO_SCRIPT set DOUT1
			else
				$GPIO_SCRIPT clear DOUT1
			fi
			if [ "$DOUT2_default" == "1" ]; then
				$GPIO_SCRIPT set DOUT2
			else
				$GPIO_SCRIPT clear DOUT2
			fi
		fi
		
		if [ "$in_out4pin" == "1" ]; then
			if [ "$DOUT3_default" == "1" ]; then
				$GPIO_SCRIPT set DOUT3
			else
				$GPIO_SCRIPT clear DOUT3
			fi
		fi
	fi
}

start()
{
	scheduler_enabled=`uci -q get output_control.scheduler.enabled`
	if [ "$scheduler_enabled" == "1" ]; then 
		schd="$(cat /etc/scheduler/config | grep $(date +%a | awk '{print tolower($0)}') | cut -d':' -f 2 | head -c $(date +%H | sed 's/\b0//g'| awk '{print ($0 + 1)}') | tail -c 1)"
		if [ $schd == "7" ]; then
				/sbin/gpio.sh set DOUT1 &
				/sbin/gpio.sh set DOUT2 &
			/sbin/gpio.sh set DOUT3 &
		elif [ $schd == "6" ]; then
				/sbin/gpio.sh clear DOUT1 &
				/sbin/gpio.sh set DOUT2 &
			/sbin/gpio.sh set DOUT3 &
		elif [ $schd == "5" ]; then
				/sbin/gpio.sh set DOUT1 &
				/sbin/gpio.sh clear DOUT2 &
			/sbin/gpio.sh set DOUT3 &
		elif [ $schd == "4" ]; then
				/sbin/gpio.sh set DOUT1 &
				/sbin/gpio.sh set DOUT2 &
			/sbin/gpio.sh clear DOUT3 &
		elif [ $schd == "3" ]; then
				/sbin/gpio.sh clear DOUT1 &
				/sbin/gpio.sh clear DOUT2 &
			/sbin/gpio.sh set DOUT3 &
		elif [ $schd == "2" ]; then
				/sbin/gpio.sh clear DOUT1 &
			/sbin/gpio.sh set DOUT2 &
			/sbin/gpio.sh clear DOUT3 &
		elif [ $schd == "1" ]; then
				/sbin/gpio.sh set DOUT1 &
				/sbin/gpio.sh clear DOUT2 &
			/sbin/gpio.sh clear DOUT3 &
		else
				/sbin/gpio.sh clear DOUT1 &
				/sbin/gpio.sh clear DOUT2 &
			/sbin/gpio.sh clear DOUT3 &
		fi
	fi
	
	#chck="$(cat /etc/crontabs/root | grep /sbin/gpio.sh)"

	#if [[ -z $chck ]]; then
		#lua /sbin/output_scheduler_cron.lua
	#fi

    sed -i "/output_control/d" /etc/crontabs/root
	config_load "output_control"
	config_foreach script_run 'rule'
	/etc/init.d/cron restart
	init_default_values
}

stop()
{
        #/sbin/gpio.sh clear DOUT1 &
        #/sbin/gpio.sh clear DOUT2 &
        #/sbin/gpio.sh clear DOUT3 &
        sed -i "/output_control/d" /etc/crontabs/root
}

restart(){
	stop
    start
}

reload_service(){
		procd_set_param file /etc/scheduler/config
        restart
}
