#!/bin/sh /etc/rc.common
# Copyright (C) 2014 Teltonika

START=43

first=$(uci -q get teltonika.sys.first_login)

start() {
    if [ "$first" != "1" ]; then
	    /usr/sbin/sim_switch change default
    fi
}
