#!/bin/sh /etc/rc.common

START=19
STOP=70

USE_PROCD=1

NAME=simd
PROG=/usr/bin/$NAME

start_service() {
	procd_open_instance

	procd_set_param command "$PROG"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

	procd_close_instance
}
