#!/bin/sh /etc/rc.common

START=70
STOP=40
USE_PROCD=15

EXTRA_COMMANDS="status"
EXTRA_HELP="	status	Status"

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/smscollect start
	procd_close_instance
}

stop_service() {
	/usr/bin/smscollect stop
}

status () {
	/usr/bin/smscollect status
}
