#!/bin/sh /etc/rc.common

START=11
STOP=98

start()
{
	if [ -e "/sys/bus/i2c/devices/0-0074/gpio" ]; then
		#echo "i2c exists\n" >> /tmp/gpiostate
		#Init pins (i2c_expander)
		/sbin/gpio.sh "export"	"DOUT1"
		/sbin/gpio.sh "dirout"	"DOUT1"
		/sbin/gpio.sh "export"	"DOUT2"
		/sbin/gpio.sh "dirout"	"DOUT2"
		/sbin/gpio.sh "export"	"DIN1"
		/sbin/gpio.sh "dirin"	"DIN1"
		/sbin/gpio.sh "export"	"DIN2"
		/sbin/gpio.sh "dirin"	"DIN2"
		/sbin/gpio.sh "export"	"SDCS"
		/sbin/gpio.sh "dirout"	"SDCS"
		/sbin/gpio.sh "export"	"RS485_R"
		/sbin/gpio.sh "dirout"	"RS485_R"
		echo 0 > /sys/class/gpio/gpio63/value
	else
		#echo "shift register exists\n" >> /tmp/gpiostate
		#Init pins (shift register)
		/sbin/gpio.sh "export"	"DOUT1"
		/sbin/gpio.sh "export"	"DOUT2"
		/sbin/gpio.sh "export"	"DOUT3"
		/sbin/gpio.sh "export"	"SDCS"
		/sbin/gpio.sh "export"	"RS485_R"
		/sbin/gpio.sh "clear"	"RS485_R"
		#SoC
		/sbin/gpio.sh "export"	"DIN1"
		/sbin/gpio.sh "dirin"	"DIN1"
		/sbin/gpio.sh "export"	"DIN2"
		/sbin/gpio.sh "dirin"	"DIN2"
		/sbin/gpio.sh "export"	"DIN3"
		/sbin/gpio.sh "dirin"	"DIN3"
	fi

	#Init RS485 driver pin
	echo 0 > /sys/class/gpio/export
	echo "out" > /sys/class/gpio/gpio0/direction
	echo 1 > /sys/class/gpio/gpio0/value
}

stop()
{
	if [ -e "/sys/bus/i2c/devices/0-0074/gpio" ]; then
		#Reset i2c gpio expander
		RESET_PIN=21
		. /lib/teltonika-gpio-functions.sh
		gpio_export_tlt $RESET_PIN
		gpio_setdir_tlt $RESET_PIN out
		gpio_write_tlt $RESET_PIN 1
	fi
}

