#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=99

SERIAL=`cat /tmp/USB_to_serial_dev_path`
ENABLED=`uci -q get usb_to_serial.rs232.enabled`

check_value(){
	value="$1"
	variable="$2"

	if [ "$value" == "" ]; then
		echo "$value"
	else
		echo "-$variable "$value""
	fi
}

if [ "$ENABLED" = "1" ]; then

	TYPE=`uci -q get usb_to_serial.rs232.type`
	SPEED=`uci -q get usb_to_serial.rs232.baudrate`
	DBITS=`uci -q get usb_to_serial.rs232.databits`
	PARITY=`uci -q get usb_to_serial.rs232.parity`
	SBITS=`uci -q get usb_to_serial.rs232.stopbits`
	FCTRL=`uci -q get usb_to_serial.rs232.flowcontrol`
	ECHO_ENABLED=`uci -q get usb_to_serial.rs232.echo_enabled`

	case "$PARITY" in
		"none")	PARITY_TMP="-parenb -parodd";;
		"odd")	PARITY_TMP="parenb parodd";;
		"even")	PARITY_TMP="parenb -parodd";;
		*)		PARITY_TMP="-parenb -parodd";;
	esac

	case "$SBITS" in
		1) SBITS_TMP="-cstopb";;
		2) SBITS_TMP="cstopb";;
		*) SBITS_TMP="-cstopb";;
	esac

	case "$FCTRL" in
		"none")		FCTRL_TMP="-crtscts -ixon -ixoff";;
		"rts/cts")	FCTRL_TMP="crtscts -ixon -ixoff";;
		"xon/xoff")	FCTRL_TMP="-crtscts ixon ixoff";;
		*)			FCTRL_TMP="-crtscts -ixon -ixoff";;
	esac
	
	if [ "$ECHO_ENABLED" == "1" ]; then
		FCTRL_TMP="$FCTRL_TMP echo"
	else
		FCTRL_TMP="$FCTRL_TMP -echo"
	fi
	
	/bin/stty -F /dev/"$SERIAL" "$SPEED" cs"$DBITS" $PARITY_TMP "$SBITS_TMP" $FCTRL_TMP

	if [ "$TYPE" = "overip" ]; then
		MODE=`uci -q get usb_to_serial.rs232.mode`
		SBITS=`check_value "$SBITS" "t"`
		DBITS=`check_value "$DBITS" "b"`
		SPEED=`check_value "$SPEED" "s"`
		PARITY=`check_value "$PARITY" "a"`
		spec_char=`uci -q get usb_to_serial.rs232.spec_char`
		if [ -z "$spec_char" ]; then
			spec_char=""
			spec_char_arg=""
		else
			spec_char_arg="-x "
		fi

		if [ "$MODE" = "server" ]; then
			MODE=`check_value "$MODE" "m"`
			TIMEOUT=`uci -q get usb_to_serial.rs232.timeout`
			TIMEOUT=`check_value "$TIMEOUT" "c"`
			IP_LISTEN=`uci -q get usb_to_serial.rs232.ip_listen`
			IP_LISTEN=`check_value "$IP_LISTEN" "i"`
			PORT_LISTEN=`uci -q get usb_to_serial.rs232.port_listen`
			PORT_LISTEN=`check_value "$PORT_LISTEN" "g"`

			DEBUG_LEVEL=`uci -q get usb_to_serial.rs232.debug`
			DEBUG_LEVEL=`check_value "$DEBUG_LEVEL" "D"`

			start_service() {
				procd_open_instance
				procd_set_param command /usr/sbin/sodog -p "/dev/$SERIAL" $DBITS $SPEED $PARITY $SBITS $MODE $DEBUG_LEVEL $TIMEOUT $IP_LISTEN $PORT_LISTEN
				procd_set_param respawn
				procd_close_instance

			}
		elif [ "$MODE" = "client" ]; then
			MODE=`check_value "$MODE" "m"`
			INTERVAL=`uci -q get usb_to_serial.rs232.recon_interval`
			INTERVAL=`check_value "$INTERVAL" "y"`
			IP_CONNECT=`uci -q get usb_to_serial.rs232.ip_connect`
			IP_CONNECT=`check_value "$IP_CONNECT" "l"`
			PORT_CONNECT=`uci -q get usb_to_serial.rs232.port_connect`
			PORT_CONNECT=`check_value "$PORT_CONNECT" "k"`

			DEBUG_LEVEL=`uci -q get usb_to_serial.rs232.debug`
			DEBUG_LEVEL=`check_value "$DEBUG_LEVEL" "D"`
			start_service() {
				procd_open_instance
				procd_set_param command /usr/sbin/sodog -p "/dev/$SERIAL" $DBITS $SPEED $PARITY $SBITS $MODE $DEBUG_LEVEL $IP_CONNECT $PORT_CONNECT $INTERVAL
				procd_set_param respawn
				procd_close_instance
			}
		elif [ "$MODE" = "bidirect" ]; then
			MODE=`check_value "$MODE" "m"`
			GPIO=`uci -q get usb_to_serial.rs232.gpio`
			GPIO=`check_value "$GPIO" "u"`
			GPIOSTATE=`uci -q get usb_to_serial.rs232.gpiostate`
			GPIOSTATE=`check_value "$GPIOSTATE" "j"`

			TIMEOUT=`uci -q get usb_to_serial.rs232.timeout`
			TIMEOUT=`check_value "$TIMEOUT" "c"`
			IP_LISTEN=`uci -q get usb_to_serial.rs232.ip_listen`
			IP_LISTEN=`check_value "$IP_LISTEN" "i"`
			PORT_LISTEN=`uci -q get usb_to_serial.rs232.port_listen`
			PORT_LISTEN=`check_value "$PORT_LISTEN" "g"`

			INTERVAL=`uci -q get usb_to_serial.rs232.recon_interval`
			INTERVAL=`check_value "$INTERVAL" "y"`
			IP_CONNECT=`uci -q get usb_to_serial.rs232.ip_connect`
			IP_CONNECT=`check_value "$IP_CONNECT" "l"`
			PORT_CONNECT=`uci -q get usb_to_serial.rs232.port_connect`
			PORT_CONNECT=`check_value "$PORT_CONNECT" "k"`

			DEBUG_LEVEL=`uci -q get usb_to_serial.rs232.debug`
			DEBUG_LEVEL=`check_value "$DEBUG_LEVEL" "D"`

			start_service() {
				procd_open_instance
				procd_set_param command /usr/sbin/sodog -p "/dev/$SERIAL" $DBITS $SPEED $PARITY $SBITS $MODE $DEBUG_LEVEL $IP_CONNECT $PORT_CONNECT $INTERVAL $TIMEOUT $IP_LISTEN $PORT_LISTEN $GPIO $GPIOSTATE
				procd_set_param respawn
				procd_close_instance
			}
		fi
	
	fi
fi
