#!/bin/sh

if [ "$#" != "1" ] && [ "$#" != "2" ]
then
	echo "usage: sendat <ATCMD> <TIMEOUT>"
	exit 1
fi

. /lib/teltonika-functions.sh

COMMAND="$1"
TIMEOUT="$2"

if [ -z $TIMEOUT ] 
then
	TIMEOUT="100"
fi

device=`uci get system.module.device 2>/dev/null`
if [ -z $device ] 
then
	echo "$0: unknown or no 3g device, aborting"
	exit 1
fi

echo -ne "$COMMAND\r" | microcom "/dev/$device" -t $TIMEOUT
