#!/bin/sh

. /lib/functions.sh

fix_enabled() {
    local config="$1"
	
    config_get proto "$config" proto
	[ "$proto" == "gre" ] || return

	config_get enabled "$config" enabled
	[ "$enabled" == "0" ] && {
		config_set "$config" disabled "1" 
	}
}

config_load network
config_foreach fix_enabled interface
uci_commit network

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@gre_tunnel[-1]
	add ucitrack gre_tunnel
	set ucitrack.@gre_tunnel[-1].init=gre_tunnel
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
