#!/bin/sh

# fix me
if [ "$INTERFACE" != "ppp" ]; then
	return
fi

if [ "$ACTION" != "ifup" ] && [ "$ACTION" != "ifdown" ]; then
	return
fi

# we store apn list in the ubus interface data field
# since interface data is destroyed upon iface restart
# we need to re-fetch apn list
/usr/sbin/operctl --fetch
