#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh
proto_init_update "$IFNAME" 0
proto_send_update "$PPP_IPPARAM"

[ -d /etc/ppp/ip-down.d ] && {
	for SCRIPT in /etc/ppp/ip-down.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}

default=`route | awk '$1 == "default" {print $1}'`
[ -z "$default" ] && {
	ifname=`uci -q get network.wan.ifname`
    if [ "$ifname" = "wwan0" -o "$ifname" = "eth2" ]; then
        ifup ppp
    else
        ifup wan
    fi
}